#!/bin/bash

# Get the C file name from the environment variable
cfile="$CFILE"

# Create the output file name with .s extension
sfile="${cfile%.*}.s"

# Generate the assembly code using gcc with the -S flag
gcc -S -masm=intel "$cfile" -o "$sfile"

